#!/bin/python

# Go to File / Options / all sheets to view all options

# options.debug = True
options.color_current_cell = "magenta"

# confirm before quitting
options.quitguard = True

# increase default width so I can see the text
options.default_width = 40

# experimental
options.save_filetype='vds'

def median(values):
  L = sorted(values)
  return L[len(L)//2]

vd.aggregator('median', median)
