#!/bin/bash
#     █████╗ ██╗     ██╗ █████╗  ██████╗███████╗ ██████╗
#    ██╔══██╗██║     ██║██╔══██╗██╔════╝██╔════╝██╔════╝
#    ███████║██║     ██║███████║╚█████╗ █████╗  ╚█████╗
#    ██╔══██║██║     ██║██╔══██║ ╚═══██╗██╔══╝   ╚═══██╗
# ██╗██║  ██║███████╗██║██║  ██║██████╔╝███████╗██████╔╝
# ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝

## recent
envar="env -0 | sort -z | tr '\0' '\n'"
edit-alias='$EDITOR $SHELL_ALIASES'
edit-env='$EDITOR $ENV'
scim='sc-im'
auto='cd $HOME/nexus/auto'
fox='browser'
##

## walk
walk='walk --icons --preview'
## walk

## sqlite3
sqlite='sqlite3 -init "$SQLITE_CONFIG"'
## sqlite3

## eza
ls='eza --icons'
ll='eza --header --all --long --icons --no-permissions --no-user --git --git-repos --total-size --time-style=relative --sort Name'
## eza

## arch
# The only solution!
arch='source arch'
## arch

## jrnl (original)
journal='/bin/jrnl'
## jrnl (original)

##
keys='gpg'
##

## git
gti='git'           # common typo
add='git add -v'
commit='git commit'
send='git send'
co='git checkout'
## git

##
icat='kitty +kitten icat --align left --use-window-size 450,450,450,450'
#jcat='icat --align left --use-window-size 400,400,400,400'
zip='tar -cvzf'
unzip='tar -xvzf'
uuid='u=$(uuidgen) ; echo $u | clipboard ; echo -e "New UUID:\n$u (copied)"'
timestamp='d=$(date +"%Y-%m-%d %H:%M:%S") ; echo $d | clipboard ; echo -e "Current timestamp:\n$d (copied)"'
pacman='sudo pacman'
mount='sudo mount'
umount='sudo umount'
#coin='coinmaster'
open='_() { xdg-open "$@" 2> /tmp/xdg-open.log & }; _'
clipboard='xclip -selection clipboard'
sqlite-gui='_() { nohup sqlitebrowser "$@" > /tmp/sqlitebrowser.log & }; _'
##

# GNU utilities
bc='bc --quiet --mathlib'
cal='echo "CALCULATOR:" ; bc'
..='cd ..'
.~="cd $HOME"
cp='cp -vi'
mv='mv -vi'
rm='rm -vi'
mkdir='mkdir -v'
rmdir='rmdir -v'
chmod='chmod -v'
grep='grep --color=auto'
la='ls -A'
l='ls -CF'
peek="tree -L 1"
D='date +%Y-%m-%d -d'
DT='date +%Y-%m-%dT%T -d'
T='date +%T -d'
# GNU

# file handling
mu='micro'
mouse='_() { nohup mousepad -o "mixed" "$@" & }; _'
md='glow'
np="notepad.exe"
npp='/mnt/c/"Program Files"/Notepad++/notepad++.exe'
tarlist='tar -tzvf'
view='wslview'
# file handling

## neomutt
mutt='EMAIL_TOKEN=$(pass "$EMAIL_TOKEN") neomutt'
## neomutt

## TaskWarrior
tk+='tk add'
tk-='tk delete'
tk~='tk modify'
## TaskWarrior

## web
web='firefox'
webmail='web https://outlook.live.com/mail/0/AQMkADAwATY0MDABLTJjOWQtZTNiYy0wMAItMDAKAC4AAAPjXhqMwf09TbNw6oo2ZfKfAQCTxSozP4SHRKrzlqtDD6thAAAA6hkQlQAAAA%3D%3D'
outlook='web https://outlook.live.com/mail'
syncthing='firefox 127.0.0.1:8384'
## web
