#!/bin/bash
#     █████╗ ██╗     ██╗ █████╗  ██████╗███████╗ ██████╗
#    ██╔══██╗██║     ██║██╔══██╗██╔════╝██╔════╝██╔════╝
#    ███████║██║     ██║███████║╚█████╗ █████╗  ╚█████╗
#    ██╔══██║██║     ██║██╔══██║ ╚═══██╗██╔══╝   ╚═══██╗
# ██╗██║  ██║███████╗██║██║  ██║██████╔╝███████╗██████╔╝
# ╚═╝╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚═════╝

## SYSTEM CONTROLS
shutdown='sudo pacman -Syu ; shutdown now'
## SYSTEM CONTROLS

## file manipulations
compress='tar -czvf'
extract='tar -xzvf' # IMPORTANT COMMAND: use to extract *.tar.gz files
tarlist='tar -tzvf'
zip='zip -v'
unzip='unzip -v'
## file manipulations

## recent
frenchar='echo -e "À\nà\nâ\nê\nî\nô\nû\né\nè"'
## recent

## arch
# The only solution!
arch='source arch'
## arch

## cd
cd='cd -P'
..='cd ..'
.-='cd -'
## cd

## clear
cls='clear -x'
## clear

## column
tab2col="column -t -s$'\t'"
## column

## cook
kook='cook recipe read'
## cook

## date
D='date +%Y-%m-%d -d'
DT='date +%Y-%m-%dT%T -d'
T='date +%T -d'
## date

## eza
# ls='eza --icons'
ll='eza --header --all --long --icons --no-permissions --no-user --git --git-repos --total-size --time-style=relative --sort Name --hyperlink'
## eza

## git
add='git add -v'
commit='git commit'
send='git send'
co='git checkout'
gist='gh gist'
## git

## GNU utilities
bc='echo "---CALCULATOR---"; bc'
cp='cp -vi'
mv='mv -vi'
rm='rm -vi'
mkdir='mkdir -v'
rmdir='rmdir -v'
chmod='chmod -v'
grep='grep --color=auto'
la='ls -A'
l='ls -CF'
peek="tree -L 1"
## GNU utilities

## gpg
keys='gpg'
encrypt='gpg --symmetric'
# decrypt='gpg --decrypt'
## gpg

## mail
m='mail'
## mail

## micro
mu='micro'
## micro

## neomutt
mutt='EMAIL_PASSWORD=$(pass "$EMAIL_PASSWORD") neomutt -F "$MUTTRC"'
## neomutt

## network manager (nmcli)
wifi='nmcli dev wifi'
connect='nmcli --ask device wifi connect'
## network manager (nmcli)

## qraft
qb='qraft' # query builder
## qraft

## remind
rem2html="perl $HOME/src/remind-05.03.02/rem2html/rem2html"
cal='rem -m -b1 -cl+2 -@'
rem-export='rem -ppp -m -b1 -@ | perl $HOME/src/remind-05.03.02/rem2html/rem2html'
edit-rem='edit $DOTREMINDERS'
edit-schedule='edit-rem'
## remind

## rendercv
gencv='rendercv render -o "resume" -nopng'
## rendercv

## sc-im
sc='sc-im'
## sc-im

## sqlite3
sqlite='sqlite3 -init "$SQLITERC"'
## sqlite3

## tabcat
tcat='tabcat2'
## tabcat

## TaskWarrior
tadd='taskwrapper add'
tmod='taskwrapper modify'
tdel='taskwrapper delete'
todo='task todo'
start='_() { task start $@ ; task todo; }; _'
## TaskWarrior

## common typos
gti='git'
sned='send'
## common typos

## various
edit='$EDITOR'
edit-env='$EDITOR $ENV'
edit-alias='$EDITOR $SHELL_ALIASES'
edit-cv='$EDITOR $VITA'
env="env -0 | sort -z | tr '\0' '\n'"
fox='browser'
icat='kitty +kitten icat --align left --use-window-size 450,450,450,450'
uuid='u=$(uuidgen) ; echo $u | clipboard ; echo -e "New UUID:\n$u (copied)"'
timestamp='d=$(date +"%Y-%m-%d %H:%M:%S") ; echo $d | clipboard ; echo -e "Current timestamp:\n$d (copied)"'
pacman='sudo pacman'
mount='sudo mount'
umount='sudo umount'
# open='_() { xdg-open "$@" 2> /tmp/xdg-open.log & }; _'
clipboard='xclip -selection clipboard'
sqlite-gui='_() { nohup sqlitebrowser "$@" > /tmp/sqlitebrowser.log & }; _'
mouse='_() { nohup mousepad -o "mixed" "$@" & }; _'
## various

## vita
cv='vita cv'
quest='vita quest'
resume='cv'
quests='quest'
qst='quest'
## vita

## walk
walk='walk --icons --preview'
## walk

## web
web='firefox'
webmail='web https://outlook.live.com/mail/0/AQMkADAwATY0MDABLTJjOWQtZTNiYy0wMAItMDAKAC4AAAPjXhqMwf09TbNw6oo2ZfKfAQCTxSozP4SHRKrzlqtDD6thAAAA6hkQlQAAAA%3D%3D'
outlook='web https://outlook.live.com/mail'
syncthing='firefox 127.0.0.1:8384'
## web

## zeit
zeit='rem -m -b1'
zeitgui=tkremind
remgui=tkremind
## zeit
