#!/bin/bash

# Use the command 'quest show' to see all defaults and overrides
# task show [KEY-VALUE PAIR]

include dark-256.theme

# GENERAL SETTINGS *******************************************************************************

  editor=$EDITOR
  verbose=affected,blank,context,footnote,label,new-id,news,project,special,sync,override,recur
  rule.precedence.color=uda,deleted,completed,active,keyword.,tag.,project.,overdue,scheduled,due.today,due,blocked,blocking,recurring,tagged
  
  print.empty.columns=yes
  exit.on.missing.db=yes
  search.case.sensitive=0
  # color.status.

# COLOR SETTINGS

  color.active=

# TABLE: JOB APPLICATIONS COLUMNS DEFINITION *****************************************************

  # Columns are defined according to vita job posting form v1.0

  # title: 
  # status: 
  # price: 
  # desc: 
  # photos: 
  # url: 
  # notes: 
  # contacts: 

  # uuid (built in)

  # title  **********************************************
    uda.title.label=title
    uda.title.type=string
    color.uda.title=color254
  # title  **********************************************

  # status  **********************************************
    uda.stat.label=status
    uda.stat.type=string
    uda.stat.values=draft,posted,removed,pending,sold
    uda.stat.default=draft
    urgency.uda.stat.coefficient=2.0
    color.uda.stat.removed=color9
    color.uda.stat.sold=gray6
  # status  **********************************************

  # price ********************************
    uda.price.label=price
    uda.price.type=numeric
    # color.uda.reference_id=color242
  # price  ********************************************

  # priority *****************************************
    urgency.uda.priority.C.coefficient=9.0   # CRITICAL
    urgency.uda.priority.H.coefficient=6.0   # HIGH
    urgency.uda.priority.M.coefficient=3.9   # MEDIUM
    urgency.uda.priority.L.coefficient=1.8   # LOW
    urgency.uda.priority.T.coefficient=-0.5  # TRIVIAL
    color.uda.priority.C=color255 on color9
    color.uda.priority.H=
    color.uda.priority.M=
    color.uda.priority.L=
    color.uda.priority.T=color240
  # priority *****************************************

  # photos ********************************
    uda.photos.label=photos
    uda.photos.type=string
    urgency.uda.photos.coefficient=1.0
    # color.uda.date_applied=color252
  # photos  ********************************

  # url **************************************
      uda.url.label=URL
      uda.url.type=string
      uda.url.indicator=...
      # color.uda.url=color249
  # url **************************************

  # notes **************************************
    uda.notes.label=notes
    uda.notes.type=string
    uda.notes.indicator=ANNOTATED
    urgency.uda.notes.coefficient=1.0
    # color.uda.resume=color250
  # notes **************************************

  # interested  **********************************************
    uda.contacts.label=contacts
    uda.contacts.type=string
    uda.contacts.indicator=CONTACTED
    urgency.uda.contacts.coefficient=3.0
    # color.uda.employer=color254
  # interested  **********************************************

# REPORTS *****************************************

  # Do $ task columns for details

  # default report
  default.command=full

  # SPECIFY:
    # 1. description
    # 2. columns
    # 3. labels
    # 4. filter
    # 5. sort
    # 6. grouping*

  # Full Table
    report.full.description="Full report of market items"
    report.full.columns=id,url.indicator,title,due.countdown,stat,priority,price,description.truncated,photos,notes.indicator,contacts.indicator,urgency,uuid.short
    report.full.labels=id,url,title,due,status,pri,price,desc,photos,notes,contacts,urg,uuid
    report.fulltable.sort=stat
  # Full Table

  # Partial report
    report.partial.description="Partial report of job applications"
    report.partial.columns=id,reference_id,due.countdown,date_applied,udastatus,resume,description.truncated,employer,location,salary
    report.partial.labels=id,reference,due,sent,status,resume,title,employer,location,salary
    report.partial.sort=entry
  # Partial Report

  # Minimal Report
      report.minimal.description="Minimal report for small windows"
      report.minimal.columns=id,reference_id,udastatus,description.truncated,employer
      report.minimal.labels=id,ref,status,title,employer
      report.minimal.sort=entry-
  # Minimal Report

  # Sort by deadline (accidently overwritten)
        report.due.description="Minimal report for small windows"
        report.due.columns=id,reference_id,udastatus,description.truncated,employer
        report.due.labels=id,ref,status,title,employer
        report.due.sort=entry-
  # Sort by deadline

  # url report
    report.url.description='show url'
    report.url.columns=id,uuid.short,url
  # url report

  # UUID REPORT
    report.uuid.description=""
    report.uuid.columns=id,uuid,description,status.short
    report.uuid.labels=id,uuid,description,st
    report.uuid.sort=id+
  # UUID REPORT

  # last inserted
    report.last_insert.description=Reports all info on last inserted task
    report.last_insert.columns=id,uuid.short,status,start.active,depends.indicator,priority,project.parent,tags,recur.indicator,wait.remaining,scheduled.remaining,due,until.remaining,description
    report.last_insert.labels=ID,UUID,Status,A,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
    report.last_insert.sort=entry-
    report.last_insert.filter=limit:1 status:pending
  # last inserted

# ALIASES ******************************************************************
  alias.insert=add # example

# TEMPLATES ******************************************************************

    # where X is uda name and V is value, F is foreground color and B is background color

    # uda.X.type=string|numeric|date|duration
    # uda.X.label=
    # uda.X.default=
    # uda.X.indicator=
    # uda.X.values=
    # 
    # color.uda.X=F on B
    # color.uda.X.V=F on B
    # color.uda.X.none=F on B
    # 
    # urgency.uda.X.coefficient=
    # urgency.uda.X.V.coefficient=

    # these are the complete configuration of a uda

# MISC *********************************************************************************
news.version=3.2.0
