#!/bin/bash

# Taskwarrior program configuration file.
# For more documentation, see https://taskwarrior.org or try 'man task', 'man task-color',
# 'man task-sync' or 'man taskrc'

# Use the command 'task show' to see all defaults and overrides

include dark-256.theme

# GENERAL ************************************************************************

  # editor summoned when doing `task edit`
    editor=$EDITOR
  # DO NOT PROPAGATE CHANGES TO OTHER CHILDREN
    recurrence.confirmation=no
  # make search case INsensitive
    search.case.sensitive=0
  # verbosity
    verbose=affected,blank,context,footnote,label,new-id,news,project,special,sync,override,recur
  # empty columns shown
    print.empty.columns=yes
  # run reports in read only to avoid useless commits and merging conflicts
    gc=0

# CONTEXTS *****************************************************************************************

    # The attributes mentioned below are added to task
    # automatically when the task is created.

    #       DOM         TAG        PRIORITY    SCHEDULED   DUE
    # -----------------------------------------------------------------------------
    #context.work.read=  +work
    #context.work.write= +work
    #context.home.read=  +home
    #context.home.write= +home

# URGENCY TUNING ***********************************************************************************

    # active/start

    urgency.active.coefficient=16
    urgency.user.tag.next.coefficient=20

    # special tags

    urgency.user.tag.auto.coefficient=1.5       # relating to my vehicles
    urgency.user.tag.coin.coefficient=1.0       # relating to my vehicles
    urgency.user.tag.rv.coefficient=4.0         # for appointments
    urgency.user.tag.sidequest.coefficient=-2.0 # sidequests should be at the bottom
    urgency.user.tag.vita.coefficient=0.5		# relating to my portfolio
    urgency.user.tag.work.coefficient=1.5       # small boost to work related tasks

    # UDAs

	  uda.priority.values=C,H,M,L,,T

	  urgency.uda.priority.C.coefficient=9.0   # CRITICAL
    urgency.uda.priority.H.coefficient=6.0   # HIGH
    urgency.uda.priority.M.coefficient=3.9   # MEDIUM
    urgency.uda.priority.L.coefficient=1.8   # LOW
    urgency.uda.priority.T.coefficient=-0.5  # TRIVIAL

    color.uda.priority.C=color255 on color173
    color.uda.priority.H=color250
    color.uda.priority.M=color245
    color.uda.priority.L=color242
    color.uda.priority.T=color240

# USER DEFINED ATTRIBUTES **************************************************************************

# 
#        color.uda.X=on green
#               Colors any task that has the user defined attribute X.
# 
#        color.uda.X.VALUE=on green
#               Colors any task that has the user defined attribute X set to VALUE.
# 
#        color.uda.X.none=on green
#               Colors any task that does not have the user defined attribute X.
       # urgency.uda.<name>.coefficient=...
       #        Presence/absence of UDA data.
       # urgency.uda.<name>.<value>.coefficient=...
       #        Specific value of UDA data.
 # uda.<name>.type=string|numeric|date|duration
 #               Defines a UDA called '<name>', of the specified type.
 # 
 #        uda.<name>.label=<column heading>
 #               Provides a default report label for the UDA called '<name>'.
 # 
 #        uda.<name>.values=A,B,C
 #               For  type  'string'  UDAs  only, this provides a comma-separated list of acceptable
 #               values. In this example, the '<name>' UDA may only contain values 'A', 'B', or 'C',
 #               but may also contain no value.
 # 
 #               Note  that  the  order  of  the value is important, and denotes the sort order from
 #               highest ('A') to lowest ('C').
 # 
 #               Note that a blank value is permitted.
 # 
 #        uda.<name>.default=...
 #               Provides a default value for the UDA called '<name>'.

    # duration ***********************************
    uda.duration.label=duration
    uda.duration.type=numeric

    # expire **************************************
    
    uda.expires.label=expires
    uda.expires.type=date
    urgency.uda.expires.coefficient=2.0 # boost before expiration
    color.uda.expires= rgb254

    # jrnl **************************************
        
    uda.jrnl.label=journal-entry
    uda.jrnl.type=string
    urgency.uda.jrnl.coefficient=1.0
    color.uda.jrnl=color255

# REPORTS ******************************************************************************************

    # default report next enhancement
    report.next.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,due.relative,until.remaining,description,urgency
    report.next.labels=ID,active,age,deps,P,project,tags,recur,sch,due,expires,desc,urg
    # report.next.context     1
    # report.next.description Most urgent tasks
    report.next.filter=status:pending -WAITING limit:15
    # report.next.sort        urgency-
    # end

    # show ids

    report.uuid.description=Reveal the UUIDs of tasks
    report.uuid.columns=id,uuid,description,status.short
    report.uuid.labels=id,uuid,description,st
    report.uuid.sort=id+

    # Tasks to do today

    report.todo.description=Tasks to be fulfilled today
    report.todo.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,due.relative,until.remaining,description,urgency
    report.todo.labels=ID,Active,Age,Deps,P,Project,Tag,Recur,S,Due,Until,Description,Urg
    report.todo.context=1
    report.todo.filter=+PENDING -WAITING ( +ACTIVE or +TOMORROW or +YESTERDAY or +next or +todo or +TODO or scheduled:today or due.before:7days) limit:page
    report.todo.sort=urgency-

    # Tasks to do today
    
    report.home.description=Tasks which can only be completed at home
    report.home.columns=id,start.age,entry.age,depends,priority,project,tags,recur,scheduled.countdown,due.relative,until.remaining,description,urgency
    report.home.labels=ID,Active,Age,Deps,P,Project,Tag,Recur,S,Due,Until,Description,Urg
    report.home.context=1
    report.home.filter=+PENDING +home limit:page
    report.homea.sort=urgency-

    # minimal report for jrnl

    report.jrnl.description=Minimal report for my journal
    report.jrnl.columns=uuid.short,description
    report.jrnl.labels=id,desc
    report.jrnl.sort=urgency+

    # adding due countdown to all report ***********************************************************

    report.all.columns=id,status.short,uuid.short,start.active,entry.age,end.age,depends.indicator,priority,project.parent,tags.count,recur.indicator,wait.remaining,scheduled.remaining,due.countdown,until.remaining,description

    # deleted tasks
    
    report.birthdays.description=Friends\'s and Family\'s Birthdays
    report.birthdays.columns=id,description,due,due.relative,status.short,urgency
    report.birthdays.labels=id,who,date,due,st,urg
    report.birthdays.sort=due+
    report.birthdays.filter=+birthday +PENDING

    # deleted tasks

    report.trash.description=List all deleted tasks
    report.trash.columns=status.short,uuid.short,description      # we need to specify the columns in the report, and the order in which those are shown
    report.trash.labels=St,uuid,desc                      # Labels are the column heading labels in the report.
    report.trash.sort=entry+
    report.trash.filter=status:deleted

    # simple

    report.simple.description=Simple list of open tasks by project
    report.simple.columns=id,project,description.count      # we need to specify the columns in the report, and the order in which those are shown
    report.simple.labels=ID,Proj,Desc                       # Labels are the column heading labels in the report.
    report.simple.sort=project+\/,entry+                    # The / solidus indicates that project is a break column, which means a blank line is inserted between unique values, for a visual grouping effect.
    report.simple.filter=status:pending limit:5             # Otherwise our report will just display all tasks

    # last inserted

    report.last_insert.description=Reports all info on last inserted task
    report.last_insert.columns=id,uuid.short,status,start.active,depends.indicator,priority,project.parent,tags,recur.indicator,wait.remaining,scheduled.remaining,due,until.remaining,description
    report.last_insert.labels=ID,UUID,Status,A,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
    report.last_insert.sort=entry-
    report.last_insert.filter=limit:1 status:pending

# MISC *********************************************************************************
news.version=3.3.0
