#!/bin/bash

# computer functions
alias shutdown='shutdown.exe /s'

# navigation
alias ..='cd ..'
alias ...="cd $HOME"
alias ll='ls -vhAlF'
alias la='ls -A'
alias l='ls -CF'
alias peek="tree -L 1"        # shows surface level content of dirs

# file handling
alias E="$EDITOR"
alias bat='batcat'
alias list='tar -tzvf'
alias md="glow"
alias note="notepad.exe"      # open with note
alias view='wslview'          # TODO mv to bin/open
alias viewdb='sqlitebrowser'  # TODO mv to bin/open

# TaskWarrior
alias ass='task +assignment'
alias ass+='task add +assignment'
alias bill+='bill add'
alias bill-='bill delete'
alias bill~='bill modify'
alias courses='t courses'
alias errands='source errands'
alias rv='task all +RV'
alias switch='source switch_task_context.sh'
alias tk+='t add'
alias tk-='t delete'
alias tk~='t modify'

# web
alias bs='firefox brightspace.algonquincollege.com/'
alias chrome="/mnt/c/'Program Files'/Google/Chrome/Application/chrome.exe"
alias chatgpt='firefox --new-tab "https://chatgpt.com/" &'

# utilities
alias c='xclip -selection clipboard' #TODO
alias cal='bc -ql'
alias D='date +%Y-%m-%d -d'
alias DT='date +%Y-%m-%dT%T -d'
alias T='date +%T -d'
alias j='journal'
alias sc='sc-im'

# common typos
alias gti='git'
