#!/bin/bash

# computer functions
alias shutdown='shutdown.exe /s'

# GNU utilities
# cp, mv, ls

# navigation
alias ..='cd ..'
alias ...="cd $HOME"
alias ll='ls -vhAlF'
alias la='ls -A'
alias l='ls -CF'
alias peek="tree -L 1"        # shows surface level content of dirs

# file handling
alias cp='cp -vi'
alias mv='mv -vi'
alias rm='rm -vi'
alias mu="$EDITOR"
alias bat='batcat'
alias list='tar -tzvf'
alias md="glow"
alias np="notepad.exe"      # open with note
# alias np+='/mnt/c/"Program Files"/Notepad++/notepad++.exe'
alias view='wslview'          # TODO mv to bin/open
alias viewdb='sqlitebrowser'  # TODO mv to bin/open
alias sqlite3='sqlite3 -batch'

# jrnl
alias jrnl="$HOME/bin/jrnl"
alias log='jrnl log'
alias jrnlc='jrnl college'

# TaskWarrior
alias ass='task +assignment'
alias ass+='task add +assignment'
alias bills='bill'
alias bill+='bill add'
alias bill-='bill delete'
alias bill~='bill modify'
alias courses='tk courses'
alias errands='source errands'
alias rv='task all +RV'
alias switch='source switch_task_context.sh'
alias tk+='tk add'
alias tk-='tk delete'
alias tk~='tk modify'

# web
alias firefox='/mnt/c/"Program Files"/Moz*/firefox.exe' # FOR WSL
alias outlook='firefox https://www.microsoft.com/en-ca/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook'
alias bs='firefox brightspace.algonquincollege.com/'
alias chrome="/mnt/c/'Program Files'/Google/Chrome/Application/chrome.exe"
alias chatgpt='firefox --new-tab "https://chatgpt.com/" &'

# utilities
alias arch="$HOME/bin/arch"
alias c='xclip -selection clipboard' #TODO
alias cal='bc -ql'
alias D='date +%Y-%m-%d -d'
alias DT='date +%Y-%m-%dT%T -d'
alias T='date +%T -d'
alias sc='sc-im'

# common typos
alias gti='git'
