#!/bin/bash

# recently added
TODO='mousepad -o "window" "$HOME/TODO" &'

# computer functions
shutdown='shutdown.exe /s'
hibernate='shutdown.exe /h'

# GNU utilities
..='cd ..'
 .~="cd $HOME"
cp='cp -vi'
mv='mv -vi'
rm='rm -vi'
mkdir='mkdir -v'
rmdir='rmdir -v'
chmod='chmod -v'
ls='ls --color=auto'
grep='grep --color=auto'
ll='ls -vhAlF'
la='ls -A'
l='ls -CF'
peek="tree -L 1"

# file handling
del='move-to-trash'
mu='micro'
mouse='_() { mousepad -o "mixed" "$@" & }; _'
md='glow'
np="notepad.exe"
npp='/mnt/c/"Program Files"/Notepad++/notepad++.exe'
tarlist='tar -tzvf'
view='wslview'
viewdb='sqlitebrowser'
sqlite3='sqlite3 -batch' # removes unnecessary message

# web
mail='firefox https://outlook.office.com/mail/'
syncthing='firefox 127.0.0.1:8384'

# jrnl
jl="$HOME/bin/jrnl"

# TaskWarrior
bills='bill'
bill+='bill add'
bill-='bill delete'
bill~='bill modify'
courses='tk courses'
errands='source errands'
rv='task next +RV'
tk+='tk add'
tk-='tk delete'
tk~='tk modify'
todo='tk todo'

# web
firefox='/mnt/c/"Program Files"/Moz*/firefox.exe' # FOR WSL
outlook='firefox https://www.microsoft.com/en-ca/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook'
chrome="/mnt/c/'Program Files'/Google/Chrome/Application/chrome.exe"
chatgpt='firefox --new-tab "https://chatgpt.com/" &'

# utilities
c='xclip -selection clipboard' # TODO:
cal='bc -ql'
D='date +%Y-%m-%d -d'
DT='date +%Y-%m-%dT%T -d'
T='date +%T -d'
sc='sc-im'

# common typos
gti='git'
