#!/bin/bash

# Taskwarrior program configuration file.
# For more documentation, see https://taskwarrior.org or try 'man task', 'man task-color',
# 'man task-sync' or 'man taskrc'

# Use the command 'task show' to see all defaults and overrides

# Files
data.location=$DATA_SOURCE/tasks
editor=$EDITOR

# CONTEXTS *****************************************************************************************

    # The attributes mentioned below are added to task
    # automatically when the task is created.

    #       DOM         TAG        PRIORITY    SCHEDULED   DUE
    # -----------------------------------------------------------------------------
    #context.work.read=  +work
    #context.work.write= +work
    #context.home.read=  +home
    #context.home.write= +home

# URGENCY TUNING ***********************************************************************************

    # special tags

    urgency.user.tag.acad.coefficient=1.5       # assignments are more urgent
    urgency.user.tag.rv.coefficient=4.0         # represents `rendez-vous`, important
    urgency.user.tag.sidequest.coefficient=-2.0 # sidequests should be at the bottom
    urgency.user.tag.todo.coefficient=3.0       # big boost to encourage commitment to task
    urgency.user.tag.work.coefficient=1.5       # small boost to work related tasks

    # UDAs

    urgency.uda.priority.H.coefficient=6.0   # default
    urgency.uda.priority.M.coefficient=3.9   # default
    urgency.uda.priority.L.coefficient=-0.5

# USER DEFINED ATTRIBUTES **************************************************************************

    # date ******************************************

    uda.date.label=date
    uda.date.type=date
    urgency.uda.date.coefficient=2.0

    # location **************************************
    #TODO

    # file ******************************************

    uda.file.label=file
    uda.file.type=string
    urgency.uda.file.coefficient=1.10
    #color.uda.file=color255

    # directory ******************************************

    uda.dir.label=DIR
    uda.dir.type=string
    urgency.uda.dir.coefficient=1.20
    color.uda.dir=color255

# REPORTS ******************************************************************************************

    # show ids

    report.uuid.description=""
    report.uuid.columns=id,uuid,description,status.short
    report.uuid.labels=id,uuid,description,st
    report.uuid.sort=id+

    # adding due countdown to all report ***********************************************************

    report.all.columns=id,status.short,uuid.short,start.active,entry.age,end.age,depends.indicator,priority,project.parent,tags.count,recur.indicator,wait.remaining,scheduled.remaining,due.countdown,until.remaining,description

    # deleted tasks
    
    report.birthdays.description="Friends\'s and Family\'s Birthdays"
    report.birthdays.columns=id,description,due,due.relative,status.short,urgency
    report.birthdays.labels=id,who,date,due,st,urg
    report.birthdays.sort=due+
    report.birthdays.filter=+birthday +PENDING

    # deleted tasks

    report.trash.description=List all deleted tasks
    report.trash.columns=status.short,uuid.short,description      # we need to specify the columns in the report, and the order in which those are shown
    report.trash.labels=St,uuid,desc                      # Labels are the column heading labels in the report.
    report.trash.sort=entry+
    report.trash.filter=status:deleted

    # simple

    report.simple.description=Simple list of open tasks by project
    report.simple.columns=id,project,description.count      # we need to specify the columns in the report, and the order in which those are shown
    report.simple.labels=ID,Proj,Desc                       # Labels are the column heading labels in the report.
    report.simple.sort=project+\/,entry+                    # The / solidus indicates that project is a break column, which means a blank line is inserted between unique values, for a visual grouping effect.
    report.simple.filter=status:pending limit:5             # Otherwise our report will just display all tasks

    # last inserted

    report.last_insert.description=Reports all info on last inserted task
    report.last_insert.columns=id,uuid.short,status,start.active,depends.indicator,priority,project.parent,tags,recur.indicator,wait.remaining,scheduled.remaining,due,until.remaining,description
    report.last_insert.labels=ID,UUID,Status,A,D,P,Project,Tags,R,Wait,Sch,Due,Until,Description
    report.last_insert.sort=entry-
    report.last_insert.filter=limit:1 status:pending

# APPEARANCE **************************************************************************

    # Color theme (uncomment one to use)
    #include light-16.theme
    #include light-256.theme
    #include dark-16.theme
    include dark-256.theme
    #include dark-red-256.theme
    #include dark-green-256.theme
    #include dark-blue-256.theme
    #include dark-violets-256.theme
    #include dark-yellow-green.theme
    #include dark-gray-256.theme
    #include dark-gray-blue-256.theme
    #include solarized-dark-256.theme
    #include solarized-light-256.theme
    #include no-color.theme

# MISC *********************************************************************************
news.version=3.1.0
