#!/bin/bash

# MY ENVIRONMENT VARIABLES (display with env)

## dependencies: parent = bashrc

export PROMPT_COMMAND="source $CFG_DIR/exit-git-ps1"   # command to be run after each command
export GITHUB='https://github.com/bytesmith-ahmad'   # my GitHub URL
export LC_ALL="C"									 # idk what this is
export LANG="C.UTF-8"                                # Encoding, same as Xenon/WSL
export EDITOR='micro'                                # default TUI editor
export VISUAL='code --new-window'                    # default GUI editor for Linux
export VISUAL_WSL='notepad.exe'                      # default GUI editor for WSL
export VISUAL=$VISUAL								 # selected visual editor
export GIT_EDITOR='code --new-window --wait'

echo 'env variables loaded'
