#!/bin/bash

# MY ENVIRONMENT VARIABLES (display with printenv)

export HOSTNAME=$(hostname)                               # Name of this computer to sign commits
export SYSTEM=$("$HOME/bin/get" os)                       # Current OS, is it Linux or is it Windows?
export CONTEXT='none'                                     # Current context: home, work, school, none, etc.
export DATABASE='archives/finances/finances.db'           # Currently connected database
export PATH="$PATH:/snap/bin"                             # Addition to path
export LC_ALL="C"
export LANG="C.UTF-8"                                     # Encoding, same as Xenon/WSL

export EDITOR='micro'                                     # default TUI editor
export VISUAL_L='gedit --new-window'                      # default GUI editor for Linux
export VISUAL_WSL='notepad.exe'                           # default GUI editor for Windows
export VISUAL=$VISUAL_WSL
export GIT_EDITOR="$EDITOR"

export github='https://github.com/bytesmith-ahmad'        # my GitHub URL
export archives="$HOME/archives"                          # my small file storage repository
export bills="$HOME/bills"                                # my bills and expenses repository
export bin="$HOME/bin"                                    # my bash scripts repository
export journal="$HOME/journal"                            # my journal entries repository
export pass="$HOME/.password-store"                       # my secrets repository
export rcfiles="$HOME/rc-files"                           # my custom configurations repository

export PATH=/home/bin:$PATH                               # in case ~/profile missing

export firefox='"/mnt/c/"Program Files"/Moz*/firefox.exe"'
