#!/bin/bash

# MY ENVIRONMENT VARIABLES (display with env)

## dependencies: parent = bashrc

export GITHUB='https://github.com/bytesmith-ahmad'   # my GitHub URL
export PROMPT_SCRIPT="$CFG_DIR/smiley-ps1"           # script containing prompt logic
export PROMPT_COMMAND="source $PROMPT_SCRIPT"        # prompt script to be run
export LC_ALL="C"									 # idk what this is
export LANG="C.UTF-8"                                # Encoding, same as Xenon/WSL
export EDITOR='micro'                                # default TUI editor
export VISUAL='code --new-window'                    # default GUI editor for Linux
export VISUAL_WSL='notepad.exe'                      # default GUI editor for WSL
export VISUAL=$VISUAL								 # selected visual editor
export GIT_EDITOR='code --new-window --wait'

echo 'env variables loaded'
