#!/bin/bash

# *********************
# | sc-im CONFIG FILE |
# *********************

# For complete documentation: /bin/bash sc-im ---> :h<enter>

## COMMANDS MAPPING

### exit scim
nmap "Q" ":q<cr>"

### save scim
nmap "<C-w>" ":w<cr>"
nmap "W" ":w<cr>"

### edit string
nnoremap "E" "Ei"

### edit number
nnoremap "e" "ei"

### table header ([f]ormat [H]eader)
nnoremap "fH" ":cellcolor \"bold=1 underline=1 fg=MAGENTA bg=DEFAULT_COLOR\"<cr>"
cnoremap "H"   "cellcolor \"bold=1 underline=1 fg=MAGENTA bg=DEFAULT_COLOR\"<cr>"

### In command mode, typing ":cc" will instantly conjure "[c]ell[c]olor "
cmap "cc" "cellcolor \""

### apply [c]olor to [t]ext
cmap "tc" "cellcolor \"bg=DEFAULT_COLOR fg="

### adds emphasis by reverting colors 
cmap "em" "cellcolor \"bold=1\"<cr>"

### reverse
cnoremap "rev" "cellcolor \"reverse=1\"<cr>"

### underline text
cmap "ul" "cellcolor \"underline=1\"<cr>"

## GENERAL

### [EXPLAIN]
set autocalc

### [STRING]
set autowrap
#set truncate
#set overlap

### this will make numbers initiate numeric value
set numeric=1
set numeric_zero
set numeric_decimal

###
#set input_bar_bottom

###
set ignorecase

###
set external_functions

#======================

#set copy_to_clipboard_delimited_tab=1
#set default_copy_to_clipboard_cmd="pbcopy <"
#set default_paste_from_clipboard_cmd="pbpaste"

## Vim scroll (has to be capital C)
#set half_page_scroll=1
#nnoremap "<C-u>" "<C-b>"
#nnoremap "<C-d>" "<C-f>"

## Formatting
#nnoremap "fd" "<C-d>"
#nnoremap "fs" ":format \"0.0##,#E+###\"<cr>"
#nnoremap "fp" ":format \"#,###,##0%\"<cr>"
#nnoremap "fa" ":format \"$#,###,##0.00 ;($#,###,##0.00)\"<cr>"

## unfreeze (fr, fc)
#nnoremap "ff" ":unfreeze<cr>"

## Left right scroll (alt-h, alt-l)
#nnoremap "˙" "zH"
#nnoremap "¬" "zL"

## Reverse the pasting so that always paste with moving references
#nnoremap "p" "Pc"
#nnoremap "Pc" "p"

## Row select
#nnoremap "V" "g0v$"

## COLORS

### NOTE: BOTH fg AND bg MUST BE DEFINED UNLESS ONE IS ALREADY SET
 
DEFINE_COLOR "skyblue" 75 50 200
# A bright yellow, good for visibility
DEFINE_COLOR "yellow" 255 215 0
# A darker yellow with a golden tone
DEFINE_COLOR "ORANGE" 255 92 0

#color "type=HEADINGS bold=1 fg=WHITE bg=BLUE"
#color "type=HEADINGS_ODD bold=1 fg=WHITE bg=BLUE"
#color "type=MODE fg=WHITE bg=DEFAULT_COLOR"
color "type=STRG fg=GREEN bg=DEFAULT_COLOR"
color "type=NUMB fg=YELLOW bg=DEFAULT_COLOR"
color "type=CELL_NEGATIVE fg=YELLOW bg=DEFAULT_COLOR"
color "type=EXPRESSION fg=ORANGE bg=DEFAULT_COLOR"
#color "type=DATEF fg=RED bg=DEFAULT_COLOR"
#color "type=CELL_SELECTION fg=BLACK bg=WHITE"
#color "type=CELL_SELECTION_SC fg=BLACK bg=WHITE"
#color "type=GRID_EVEN fg=DEFAULT_COLOR bg=DEFAULT_COLOR"
#color "type=GRID_ODD fg=DEFAULT_COLOR bg=DEFAULT_COLOR"
#color "type=CELL_ERROR fg=BLACK bg=RED"
#color "type=INFO_MSG fg=WHITE bg=GREEN"
#color "type=ERROR_MSG fg=BLACK bg=RED"
#color "type=CELL_ID fg=BLUE bg=DEFAULT_COLOR"
#color "type=CELL_FORMAT fg=WHITE bg=DEFAULT_COLOR"
#color "type=CELL_CONTENT fg=GREEN bg=DEFAULT_COLOR"
#color "type=WELCOME fg=GREEN bg=BLACK"
#color "type=NORMAL fg=GREEN bg=BLACK"
#color "type=INPUT fg=WHITE bg=DEFAULT_COLOR"
#color "type=HELP_HIGHLIGHT fg=GREEN bg=WHITE"
#=========================
