#!/bin/bash

# Symlinks description file

## 
## Automatically create symlinks spread throughout the filesystem.
##
## To use set ORIGIN FILE = DESTINATION FILE
## Use absolute path for ORIGIN files
## Use paths relative to this folder (dotfiles) for DESTINATION files.
##

### shell

~/.bashrc = shell/config
~/.env    = shell/.env

### mutt

~/.muttrc = mutt/config

### sc-im

~/.config/sc-im/scimrc = scim/config

### sqlitebrowser

~/.config/sqlitebrowser/sqlitebrowser.conf = sqlitebrowser/conf

### kitty terminal

~/.config/kitty/kitty.conf = kitty/kitty.conf
/usr/lib/kitty/logo/kitty.png = kitty/kitty.png
/usr/lib/kitty/logo/kitty-128.png = kitty/kitty-128.png

### xfce4

#### xfce4 settings cannot be symlinked (or can they?? Try hardlinks?). Must replace all files.
